version: '2'

volumes:
  spotifycache:
  snapcast:

services:

  # Core services
  audio:
    build: ./core/audio
    privileged: true
    labels:
      io.balena.features.dbus: 1
    ports:
      - 4317:4317
    volumes:
      - snapcast:/var/cache/snapcast

  sound-supervisor:
    build: ./core/sound-supervisor
    network_mode: host
    ports:
      - 3000:3000
    labels:
      io.balena.features.supervisor-api: 1

  # Plugins
  airplay:
    build: ./plugins/airplay
    restart: on-failure
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: 1

  spotify:
    build: ./plugins/spotify
    restart: on-failure
    privileged: true
    network_mode: host
    volumes:
      - spotifycache:/var/cache/raspotify
